# Generated by Django 2.1.2 on 2019-01-16 21:47
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='recipients',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Recipients'),
        ),
    ]
